project:
  type: website

website:
  title: "Eleana_Cabello"
  navbar:
    right:
      - icon: house
        href: index.qmd
        text: Home
      - icon: hammer
        href: projects.qmd
        text: Projects

format:
  html:
    theme: styles.scss
    mainfont: Bitcount 
    toc: true



